### ISSUE TITLE
Different view modes 

### ISSUE THREAD

**Issue by Tunous** [Tunous/SwipeNews-Issues#11]
Additional customization options allowing the users to setup layout exactly how they want. 

# View modes
- [x] Compact 
  The default view mode looking as in current version. 

- [x] Cards 
  View mode where articles are displayed inside of cards. 

- [ ] Full height 
  View mode where articles take full visible height. 

# Settings

Parts of interface which can be customized by the users in an easy to use UI.

- [x] Image
  - [x] Visibility
    - [x] Visible
    - [x] Gone
  - [x] Size
    - [x] Thumbnail
    - [x] Full width
  - [x] Position
    - [x] Left side
    - [x] Right side
    - [x] Top
    - [x] Middle
    - [x] Bottom
- [x] Details 
  - [x] Visible
  - [x] Gone
- [x] Short summary
  - [x] Visible
  - [x] Gone

# Inspiration

https://dribbble.com/shots/2187254-feedly-Redesign-Concept-Nexus-5/attachments/403685

https://medium.muz.li/40-inspiring-examples-of-mobile-feeds-9dcc9f5c47c3#.c258now7v

https://material.uplabs.com/posts/newsfeed

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Different view modes](https://trello.com/c/RdmSpDCT/785-different-view-modes)

**Comment by Tunous** [comment]
# General tasks

- [ ] Create view mode customization screen
  - [ ] View mode selection
  - [ ] Image position/visibility selection
  - [ ] Details text visibility
  - [ ] Article summary visibility
  - [ ] Action bar visibility?
- [ ] Store user settings
- [ ] Create action bar customization?

# Tasks for card mode

- [ ] Color of background behind cards
- [ ] Disable dividers
- [ ] Make card background correctly update on read state changes
- [ ] Decide on size of spacing between cards

___

I might add action bar settings later after general customization is done.

**Comment by Tunous** [comment]
Some progress images:

![screenshot from 2016-11-10 17-36-21](https://cloud.githubusercontent.com/assets/5156340/20185823/ca15d0a2-a76d-11e6-9f9c-3e53dab21555.png)
![screenshot from 2016-11-10 17-37-11](https://cloud.githubusercontent.com/assets/5156340/20185821/ca141578-a76d-11e6-9648-c88bb9197fe9.png)
![screenshot from 2016-11-10 17-38-13](https://cloud.githubusercontent.com/assets/5156340/20185820/ca139472-a76d-11e6-85c4-30a65dcc45de.png)
![screenshot from 2016-11-10 17-39-07](https://cloud.githubusercontent.com/assets/5156340/20185822/ca158fd4-a76d-11e6-955c-e74c8a4fce2d.png)

**Comment by Tunous** [comment]
![screenshot_1478958998](https://cloud.githubusercontent.com/assets/5156340/20238324/8a04d14e-a8e8-11e6-9ae5-d789a130daa6.png)
![screenshot_1478959020](https://cloud.githubusercontent.com/assets/5156340/20238321/8a03daf0-a8e8-11e6-836a-431d9357d56e.png)
![screenshot_1478959053](https://cloud.githubusercontent.com/assets/5156340/20238322/8a048dba-a8e8-11e6-93fb-809850179840.png)
![screenshot_1478959079](https://cloud.githubusercontent.com/assets/5156340/20238323/8a049cec-a8e8-11e6-8b11-cd0879391793.png)
